package taiji.org.donkeymgr.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import taiji.org.donkeymgr.dao.UploadImageInfo;
import taiji.org.donkeymgr.dao.Donkey;

import taiji.org.donkeymgr.dao.UploadImageInfoDao;
import taiji.org.donkeymgr.dao.DonkeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uploadImageInfoDaoConfig;
    private final DaoConfig donkeyDaoConfig;

    private final UploadImageInfoDao uploadImageInfoDao;
    private final DonkeyDao donkeyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uploadImageInfoDaoConfig = daoConfigMap.get(UploadImageInfoDao.class).clone();
        uploadImageInfoDaoConfig.initIdentityScope(type);

        donkeyDaoConfig = daoConfigMap.get(DonkeyDao.class).clone();
        donkeyDaoConfig.initIdentityScope(type);

        uploadImageInfoDao = new UploadImageInfoDao(uploadImageInfoDaoConfig, this);
        donkeyDao = new DonkeyDao(donkeyDaoConfig, this);

        registerDao(UploadImageInfo.class, uploadImageInfoDao);
        registerDao(Donkey.class, donkeyDao);
    }
    
    public void clear() {
        uploadImageInfoDaoConfig.getIdentityScope().clear();
        donkeyDaoConfig.getIdentityScope().clear();
    }

    public UploadImageInfoDao getUploadImageInfoDao() {
        return uploadImageInfoDao;
    }

    public DonkeyDao getDonkeyDao() {
        return donkeyDao;
    }

}
