package taiji.org.donkeymgr.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig donkeyDaoConfig;

    private final DonkeyDao donkeyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        donkeyDaoConfig = daoConfigMap.get(DonkeyDao.class).clone();
        donkeyDaoConfig.initIdentityScope(type);

        donkeyDao = new DonkeyDao(donkeyDaoConfig, this);

        registerDao(Donkey.class, donkeyDao);
    }
    
    public void clear() {
        donkeyDaoConfig.getIdentityScope().clear();
    }

    public DonkeyDao getDonkeyDao() {
        return donkeyDao;
    }

}
