package taiji.org.donkeymgr.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DONKEY".
 */
public class Donkey {

    private Long id;
    private int sn;
    private String farmer;
    private String breedaddress;
    private String supplier;
    private String supplyaddress;
    private String dealtime;
    private String supplytime;
    private String breed;
    private String sex;
    private String agewhendeal;
    private String agewhenkill;
    private String feedpattern;
    private String forage;
    private String feedstatus;
    private String healthstatus;
    private String breedstatus;
    private String killdepartment;
    private String killplace;
    private String killtime;
    private String freshkeepmethod;
    private String freshkeeptime;
    private String splitstatus;
    private String processstatus;
    private String qualitystatus;
    private String QC;
    private String QA;
    private String furquality;
    private String reserved;
    private String factorytime;
    private Long version;
    private Long syncver;
    private Long idonserver;
    private Boolean syncing;
    private Boolean deleteflag;

    public Donkey() {
    }

    public Donkey(Long id) {
        this.id = id;
    }

    public boolean hasSync(){
        return syncver == version;
    }

    public Donkey(Long id, int sn, String farmer, String breedaddress, String supplier, String supplyaddress, String dealtime, String supplytime, String breed, String sex, String agewhendeal, String agewhenkill, String feedpattern, String forage, String feedstatus, String healthstatus, String breedstatus, String killdepartment, String killplace, String killtime, String freshkeepmethod, String freshkeeptime, String splitstatus, String processstatus, String qualitystatus, String QC, String QA, String furquality, String reserved, String factorytime, Long version, Long syncver, Long idonserver, Boolean syncing, Boolean deleteflag) {
        this.id = id;
        this.sn = sn;
        this.farmer = farmer;
        this.breedaddress = breedaddress;
        this.supplier = supplier;
        this.supplyaddress = supplyaddress;
        this.dealtime = dealtime;
        this.supplytime = supplytime;
        this.breed = breed;
        this.sex = sex;
        this.agewhendeal = agewhendeal;
        this.agewhenkill = agewhenkill;
        this.feedpattern = feedpattern;
        this.forage = forage;
        this.feedstatus = feedstatus;
        this.healthstatus = healthstatus;
        this.breedstatus = breedstatus;
        this.killdepartment = killdepartment;
        this.killplace = killplace;
        this.killtime = killtime;
        this.freshkeepmethod = freshkeepmethod;
        this.freshkeeptime = freshkeeptime;
        this.splitstatus = splitstatus;
        this.processstatus = processstatus;
        this.qualitystatus = qualitystatus;
        this.QC = QC;
        this.QA = QA;
        this.furquality = furquality;
        this.reserved = reserved;
        this.factorytime = factorytime;
        this.version = version;
        this.syncver = syncver;
        this.idonserver = idonserver;
        this.syncing = syncing;
        this.deleteflag = deleteflag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSn() {
        return sn;
    }

    public void setSn(int sn) {
        this.sn = sn;
    }

    public String getFarmer() {
        return farmer;
    }

    public void setFarmer(String farmer) {
        this.farmer = farmer;
    }

    public String getBreedaddress() {
        return breedaddress;
    }

    public void setBreedaddress(String breedaddress) {
        this.breedaddress = breedaddress;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getSupplyaddress() {
        return supplyaddress;
    }

    public void setSupplyaddress(String supplyaddress) {
        this.supplyaddress = supplyaddress;
    }

    public String getDealtime() {
        return dealtime;
    }

    public void setDealtime(String dealtime) {
        this.dealtime = dealtime;
    }

    public String getSupplytime() {
        return supplytime;
    }

    public void setSupplytime(String supplytime) {
        this.supplytime = supplytime;
    }

    public String getBreed() {
        return breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getAgewhendeal() {
        return agewhendeal;
    }

    public void setAgewhendeal(String agewhendeal) {
        this.agewhendeal = agewhendeal;
    }

    public String getAgewhenkill() {
        return agewhenkill;
    }

    public void setAgewhenkill(String agewhenkill) {
        this.agewhenkill = agewhenkill;
    }

    public String getFeedpattern() {
        return feedpattern;
    }

    public void setFeedpattern(String feedpattern) {
        this.feedpattern = feedpattern;
    }

    public String getForage() {
        return forage;
    }

    public void setForage(String forage) {
        this.forage = forage;
    }

    public String getFeedstatus() {
        return feedstatus;
    }

    public void setFeedstatus(String feedstatus) {
        this.feedstatus = feedstatus;
    }

    public String getHealthstatus() {
        return healthstatus;
    }

    public void setHealthstatus(String healthstatus) {
        this.healthstatus = healthstatus;
    }

    public String getBreedstatus() {
        return breedstatus;
    }

    public void setBreedstatus(String breedstatus) {
        this.breedstatus = breedstatus;
    }

    public String getKilldepartment() {
        return killdepartment;
    }

    public void setKilldepartment(String killdepartment) {
        this.killdepartment = killdepartment;
    }

    public String getKillplace() {
        return killplace;
    }

    public void setKillplace(String killplace) {
        this.killplace = killplace;
    }

    public String getKilltime() {
        return killtime;
    }

    public void setKilltime(String killtime) {
        this.killtime = killtime;
    }

    public String getFreshkeepmethod() {
        return freshkeepmethod;
    }

    public void setFreshkeepmethod(String freshkeepmethod) {
        this.freshkeepmethod = freshkeepmethod;
    }

    public String getFreshkeeptime() {
        return freshkeeptime;
    }

    public void setFreshkeeptime(String freshkeeptime) {
        this.freshkeeptime = freshkeeptime;
    }

    public String getSplitstatus() {
        return splitstatus;
    }

    public void setSplitstatus(String splitstatus) {
        this.splitstatus = splitstatus;
    }

    public String getProcessstatus() {
        return processstatus;
    }

    public void setProcessstatus(String processstatus) {
        this.processstatus = processstatus;
    }

    public String getQualitystatus() {
        return qualitystatus;
    }

    public void setQualitystatus(String qualitystatus) {
        this.qualitystatus = qualitystatus;
    }

    public String getQC() {
        return QC;
    }

    public void setQC(String QC) {
        this.QC = QC;
    }

    public String getQA() {
        return QA;
    }

    public void setQA(String QA) {
        this.QA = QA;
    }

    public String getFurquality() {
        return furquality;
    }

    public void setFurquality(String furquality) {
        this.furquality = furquality;
    }

    public String getReserved() {
        return reserved;
    }

    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    public String getFactorytime() {
        return factorytime;
    }

    public void setFactorytime(String factorytime) {
        this.factorytime = factorytime;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getSyncver() {
        return syncver;
    }

    public void setSyncver(Long syncver) {
        this.syncver = syncver;
    }

    public Long getIdonserver() {
        return idonserver;
    }

    public void setIdonserver(Long idonserver) {
        this.idonserver = idonserver;
    }

    public Boolean getSyncing() {
        return syncing;
    }

    public void setSyncing(Boolean syncing) {
        this.syncing = syncing;
    }

    public Boolean getDeleteflag() {
        return deleteflag;
    }

    public void setDeleteflag(Boolean deleteflag) {
        this.deleteflag = deleteflag;
    }

}
